#!/usr/bin/env bash

set -o errexit -o noclobber -o nounset -o pipefail

CONFIG=$( cd "$( dirname "$0" )" && pwd )
cd $CONFIG

EXCLUDED=FILES.exclude
DEST=~


check_files()
{
    ALL_FILES=$(rsync --dry-run --existing --exclude-from=$EXCLUDED -a . | awk '{print $5}') 
    for f in $ALL_FILES; do
        if [ -f ~/$f ]; then     
            if [ ~/$f -nt $f ]; then
                echo "~/$f is newer"
            fi
            if [ $(stat -f "%Sp" ~/$f) != "$(stat -f "%Sp" $f)" ]; then 
                echo "~/$f permissions differ"
            fi
            diff -q ~/$f $f
        fi
    done
}

install_files()
{
    cd $CONFIG
    rsync --exclude-from=$EXCLUDED -av --no-perms . $DEST
}


usage()
{
cat <<EOF
usage: config [ -h ] ( -i | -c )
  
     Options:
      
     -h      this help text
     -i      install config files in \$HOME=$HOME   
     -c      check config files

EOF
}


CMD=
OPTIND=1 # Reset is necessary if getopts was used previously in the script.
while getopts "hic3:" opt; do
    case $opt in
        h)
            usage
            exit 0
            ;;
        i)  
            CMD="install"
            ;;
        c)  
            CMD="check"
            ;;
        3)  
            echo "THREE: $OPTARG"
            ;;
        
        \?) 
            usage >&2 
            exit 1
            ;;
    esac
done
shift $((OPTIND-1)) # Shift off the options and optional --.
dotfile=${1:-""}


case $CMD in
    install)
        install_files
        ;;
    check)
        check_files
        ;;
    *)
        echo $0: missing option 
        usage
        ;;
esac














